name: Fortify ScanCentral SAST Scan
on:
  workflow_dispatch:
  schedule:
    - cron: 0 3 5 * *

jobs:
  Fortify-SAST:
    runs-on: ubuntu-latest
    name: Run Fortify Scan
    steps:
      - uses: knockrentals/gh-action-fortify-scan@v1
        with:
          fod-user: ${{ secrets.FOD_USER }}
          fod-pat: ${{ secrets.FOD_PAT }}
          fod-release-id: 786331
